-- Migration: Remove all foreign key constraints from trading database
-- Date: 2026-03-16
-- Description: This SQL script removes all foreign key constraints while preserving
--              the integer columns and their indexes for query performance.

-- Note: Before running this script, you need to find the actual constraint names
-- in your database as they may be auto-generated.

-- Use this query to find constraint names:
-- SELECT
--     CONSTRAINT_NAME,
--     TABLE_NAME,
--     COLUMN_NAME,
--     REFERENCED_TABLE_NAME
-- FROM
--     INFORMATION_SCHEMA.KEY_COLUMN_USAGE
-- WHERE
--     TABLE_SCHEMA = 'hedge-fund'
--     AND REFERENCED_TABLE_NAME IS NOT NULL;

-- ============================================================================
-- Drop foreign keys from trading_decisions table
-- ============================================================================
-- The constraint name will be auto-generated by MySQL, typically in format:
-- trading_decisions_ibfk_1 or similar

-- Uncomment and update the constraint name after running the query above:
-- ALTER TABLE trading_decisions DROP FOREIGN KEY <constraint_name_here>;

-- Example:
-- ALTER TABLE trading_decisions DROP FOREIGN KEY trading_decisions_ibfk_1;


-- ============================================================================
-- Drop foreign keys from analyst_analyses table
-- ============================================================================
-- Uncomment and update the constraint name after running the query above:
-- ALTER TABLE analyst_analyses DROP FOREIGN KEY <constraint_name_here>;

-- Example:
-- ALTER TABLE analyst_analyses DROP FOREIGN KEY analyst_analyses_ibfk_1;


-- ============================================================================
-- Drop foreign keys from market_data table
-- ============================================================================
-- Uncomment and update the constraint name after running the query above:
-- ALTER TABLE market_data DROP FOREIGN KEY <constraint_name_here>;

-- Example:
-- ALTER TABLE market_data DROP FOREIGN KEY market_data_ibfk_1;


-- ============================================================================
-- Drop foreign keys from performance_metrics table
-- ============================================================================
-- Uncomment and update the constraint name after running the query above:
-- ALTER TABLE performance_metrics DROP FOREIGN KEY <constraint_name_here>;

-- Example:
-- ALTER TABLE performance_metrics DROP FOREIGN KEY performance_metrics_ibfk_1;


-- ============================================================================
-- Verification
-- ============================================================================
-- After running the script, verify no foreign keys remain:
-- SELECT
--     CONSTRAINT_NAME,
--     TABLE_NAME,
--     COLUMN_NAME
-- FROM
--     INFORMATION_SCHEMA.KEY_COLUMN_USAGE
-- WHERE
--     TABLE_SCHEMA = 'hedge-fund'
--     AND REFERENCED_TABLE_NAME IS NOT NULL;
