services:
  backtester:
    build:
      context: .
      dockerfile: Dockerfile
    image: guestros/ai-hedge-fund:latest
    volumes:
      - ./.env:/app/.env
    command: poetry run python src/backtester.py --ticker AAPL,MSFT,NVDA,AAPL,GOOGL,MSFT,NVDA,TSLA --analysts-all --model gemini-2.5-flash
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    tty: true
    stdin_open: true

