{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.name }}
      release: "{{ .Release.Name }}"
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
              release: "{{ .Release.Name }}"
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-network-policy
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      release: "{{ .Release.Name }}"
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.backend.name }}
              release: "{{ .Release.Name }}"
      ports:
        - protocol: TCP
          port: 8000
{{- end }}